### Numpy

- Pandas : https://pasnds.pydata.org/
- Numpy : https://numpy.org/

- 수치해석 수학적 처리를 위한 라이브러리(모듈) - Scipy, Pandas, Maptploplib


In [2]:
! pip list


Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
colorama          0.4.6
comm              0.1.3
debugpy           1.6.7
decorator         5.1.1
executing         1.2.0
Faker             18.11.1
ipykernel         6.23.2
ipython           8.14.0
jedi              0.18.2
jupyter_client    8.2.0
jupyter_core      5.3.1
matplotlib-inline 0.1.6
nest-asyncio      1.5.6
numpy             1.25.0
packaging         23.1
pandas            2.0.2
parso             0.8.3
pickleshare       0.7.5
pip               23.1.2
platformdirs      3.7.0
prompt-toolkit    3.0.38
psutil            5.9.5
pure-eval         0.2.2
Pygments          2.15.1
python-dateutil   2.8.2
pytz              2023.3
pywin32           306
pyzmq             25.1.0
setuptools        65.5.0
six               1.16.0
somepackage       1.2.3
stack-data        0.6.2
tornado           6.3.2
traitlets         5.9.0
tzdata            2023.3
wcwidth           0.2.6


In [4]:
! pip install numpy

In [5]:
!pip install pandas

In [6]:
#import

import pandas as pd
import numpy as np

#### numpy를  쓰는 이유
- python 리스트를 만들면(1,000,000건) -260ms
- numpy 배열을 만들면(1,000,000건) -34.3ms(8배정도 빠름)

In [8]:
py_list = list(range(1_000_000)) # 100만건 리스트 만들기

In [10]:
np_arr = np.arange(1_000_000)

In [14]:
## 파이썬 리스트 사용
%timeit for _ in range(10) : py_list2 = py_list *2

144 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
# _ 는 사용안한다는 말 그냥 돌리기만 한다는 말
%timeit for _ in range(10) : np_arr2 = np_arr *2

13.6 ms ± 284 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### 넘파이로 배열 생성, 연산등
- 파이썬 리스트는 +(리스트끼리), *(숫자만)연산 밖에 없음
- 행렬(벡터) ~

In [16]:
# 1차원 배열
np_arr1 = np.array([1,3,5])
np_arr1

array([1, 3, 5])

In [17]:
# 2차원 배열
np_arr2 = np.array([[1,3,5],[1,3,5]])
np_arr2

array([[1, 3, 5],
       [1, 3, 5]])

In [19]:
# 3차원 배열
np_arr3 = np.array([[[0,2,4],[8,10,12]],[[1,3,5],[7,9,12]]])
np_arr3

array([[[ 0,  2,  4],
        [ 8, 10, 12]],

       [[ 1,  3,  5],
        [ 7,  9, 12]]])

In [21]:
# 파이썬 기본 리스트(배열)
list1 = [1, 3, 5]
list1

[1, 3, 5]

In [23]:
# [1, 3, 5], [1, 3, 5] 는 튜플로 1차원 배열이 두개 만들어짐 -> numpy에서는 허용이 안됨
# [[1, 3, 5], [1, 3, 5]]
list2 = [[1, 3, 5], [1, 3, 5]]
list2

[[1, 3, 5], [1, 3, 5]]

In [24]:
# 길이가 4인 1차원 배열을 전부 0으로 채울것
np_arr4 = np.zeros(4)
np_arr4

array([0., 0., 0., 0.])

In [25]:
np_arr5 =np.zeros([2,3])
np_arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.random.randn(2,3)

array([[-0.60040312,  0.37432108, -0.37357214],
       [-0.4446781 ,  1.05702959,  0.82869453]])

In [30]:
np_arr7= np.arange(10)
np_arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 파이썬에서 리스트 만든 다음에 numpy형태의 배열로 변경
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# 연산
np_arr7 +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
# 파이썬 리스트는 +(리스트끼리만), *(숫자만)
list(np_arr7) +2 # 더하기 x , 리스트끼리만 가능

TypeError: can only concatenate list (not "int") to list

In [33]:
np_arr7 * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [34]:
np_arr7 /4

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25])

In [36]:
np_arr7 // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [37]:
np_arr7 + np_arr7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# 파이썬 리스트 + contect(두 리스트를 함침)
list(range(10)) + list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
# 비교연산
(np_arr7 + np_arr7) < 9

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [40]:
(np_arr7 + np_arr7) != 9

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [43]:
# 인덱스 크기를 벗어나면 IndexError
np_arr7[np_arr7 < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np_arr7[np_arr7 < 5]

array([0, 1, 2, 3, 4])

In [44]:
[x for x in range(10) if x < 5] # 리스트 내포

[0, 1, 2, 3, 4]

In [45]:
np_arr7[3:9] # 뒤에 인덱스는 항상 -1

array([3, 4, 5, 6, 7, 8])

In [46]:
# 2차원 배열에서 값 조회
np_arr2[1][2]

5

In [47]:
np_arr2[1,2] =9
np_arr2

array([[1, 3, 5],
       [1, 3, 9]])

In [48]:
# 값 변경(치환)
np_arr7[np_arr7 < 5] = 100
np_arr7

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

#### 속성
 - shape, dtype, T

In [50]:
# 1차원 -> 열만있는형태?(,3)
np_arr1.shape

(3,)

In [51]:
# 2차원 열과 행이 존재
np_arr2.shape

(2, 3)

In [52]:
np_arr2.dtype

dtype('int32')

In [53]:
np_arr2.T.shape

(3, 2)

#### 기타 함수

In [56]:
np_arr8 = np.arange(10)
np_arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
np_arr8.sum()

45

In [62]:
np_arr8.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [64]:
np_arr9 = np.random.randn(10)
np_arr9

array([ 1.06653849, -0.03273921,  0.08423983, -0.79256518,  0.38453289,
        0.27146054, -0.29581685,  0.11650622, -0.37719224,  0.99975633])

In [65]:
# 오름차순 정렬
np_arr9.sort()

In [66]:
np_arr9

array([-0.79256518, -0.37719224, -0.29581685, -0.03273921,  0.08423983,
        0.11650622,  0.27146054,  0.38453289,  0.99975633,  1.06653849])

In [67]:
# 내림차순 정렬
-np.sort(-np_arr9)

array([ 1.06653849,  0.99975633,  0.38453289,  0.27146054,  0.11650622,
        0.08423983, -0.03273921, -0.29581685, -0.37719224, -0.79256518])

#### 테스트용 테이터프레임 예제

In [69]:
# 테스트용 더미데이터프레임 만들기
size = 10
df = pd.DataFrame({
    'class' : [['A','B','C','D','F'][np.random.randint(0,5)] for i in range(0,size)],
    'year' : [np.random.randint(2010,2024) for i in range(0,size)],
    'month' : [np.random.randint(1,13) for i in range(0,size)],
    'val1' : [np.random.randint(1,11) for i in range(0,size)],
    'val2' : [np.random.randint(100,1000) for i in range(0,size)],
    'val3' : [np.random.randint(10000,20000) for i in range(0,size)],
})
df

class  year  month  val1  val2   val3
0     D  2014      4    10   104  14114
1     D  2018      8     3   913  17245
2     B  2015     11     9   368  16305
3     D  2023      9     6   886  15333
4     B  2023      1     1   263  13335
5     A  2017     12     7   669  10125
6     D  2023     12     9   957  11896
7     A  2016     12     7   744  11460
8     D  2010      5     2   395  12221
9     D  2019      9     3   566  10378

In [70]:
df.dtypes

class    object
year      int64
month     int64
val1      int64
val2      int64
val3      int64
dtype: object

In [71]:
df.T

0      1      2      3      4      5      6      7      8      9
class      D      D      B      D      B      A      D      A      D      D
year    2014   2018   2015   2023   2023   2017   2023   2016   2010   2019
month      4      8     11      9      1     12     12     12      5      9
val1      10      3      9      6      1      7      9      7      2      3
val2     104    913    368    886    263    669    957    744    395    566
val3   14114  17245  16305  15333  13335  10125  11896  11460  12221  10378